# These are supported funding model platforms

github: [viptvx]
patreon: viptvx
open_collective: viptv
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/viptv 
custom: # Replace with a single custom sponsorship URL